/var/log/nginx/*.log {
    daily
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    create 0640 www-data adm
    sharedscripts
    postrotate
        /usr/sbin/start-stop-daemon --stop --signal USR1 --quiet --pidfile /run/nginx.pid --name nginx
    endscript
}
