log_format onyx_geo escape=json '{'
    '"time":"$time_iso8601",'
    '"host":"$host",'
    '"clientIp":"$http_cf_connecting_ip",'
    '"proxyIp":"$remote_addr",'
    '"method":"$request_method",'
    '"path":"$request_uri",'
    '"status":$status,'
    '"userAgent":"$http_user_agent"'
'}';
